openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: okthess-community-6071
  url: https://83.212.100.226:6071/v1
security:
- {}
tags:
- description: not yet ready
  name: contact
paths:
  /contact:
    post:
      operationId: createcontact
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/contact'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/contact'
          description: successful operation
      summary: Creates the data
      tags:
      - contact
      x-eov-operation-handler: controllers/ContactController
  /contact/{contactId}:
    delete:
      operationId: deletecontact
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: contactId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - contact
      x-eov-operation-handler: controllers/ContactController
    get:
      operationId: getcontact
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: contactId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/contact'
          description: successful operation
      summary: Get the element
      tags:
      - contact
      x-eov-operation-handler: controllers/ContactController
    put:
      operationId: updatecontact
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: contactId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/contact'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/contact'
          description: successful operation
      summary: Updates the element
      tags:
      - contact
      x-eov-operation-handler: controllers/ContactController
  /contact/getAll:
    get:
      operationId: getAllcontact
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/contact'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - contact
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/ContactController
  /contact/getByParams:
    get:
      operationId: getByParamscontact
      parameters:
      - description: the query based on which the search is performed
        explode: true
        in: query
        name: filter
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/contact'
                type: array
          description: successful operation
      summary: Get all the data based on user query
      tags:
      - contact
      x-method-get-by-params: "true"
      x-eov-operation-handler: controllers/ContactController
components:
  schemas:
    contact:
      example:
        company: company
        comment: comment
        _id: _id
        fullname: fullname
      properties:
        _id:
          type: string
        fullname:
          type: string
        company:
          type: string
        comment:
          type: string
      required:
      - comment
      - company
      - fullname
      type: object
